# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Kotlin CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 19
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Check formatting
        run: ./gradlew spotlessCheck

  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 19
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: echo 'no' | ./gradlew build --scan -x test
  create-artifacts:
    #needs: [ build, format ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 19
      - name: Build app
        run: ./gradlew assembleDebug
      #- uses: sparkfabrik/android-build-action@v1.5.0
        #with:
          #project-path: app
          #output-path: FestFriend.apk
          #browserstack-upload: true
          #browserstack-username: ${{ secrets.BROWSERSTACK_USERNAME }}
          #browserstack-access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          #ruby-version: "2.7.5"
          #bundler-version: "2.3.26"
          #fastlane-env: "debug"
      - name: LS
        run: |
          ls .
        #  ls /app/
        #  ls /app/build
        #  ls /app/build/outputs
        #  ls /app/build/outputs/apk
        #  ls /app/build/outputs/apk/debug
        #  ls /app/build/outputs/apk/debug/app-debug.apk
      - uses: actions/upload-artifact@v2
        with:
          name: FestFriendDebug.apk
          path: app/build/outputs/apk/debug/app-debug.apk